spring:
  application:
    name: zuul-server
  kafka:
    admin:
      client-id: order-server
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#  sleuth:
#    sampler:
#      percentage: 1.0
#  zipkin:
#    rabbitmq:
#      queue: zipkin
#    base-url: http://localhost:1080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
# 打印转发细节
#logging:
#  level:
#    com.netflix: DEBUG

zuul:
  prefix: /api
  # 为 true 时，转发忽略前缀
  strip-prefix: true
  routes:
    # 指定微服务的访问路径 1，即可用api-a替代user-service访问
#    api-a: # 路由的名称，任意取名
#      serviceId: user-service
#      path: /api-a/**
    # 指定微服务的访问路径 2，即可用service替代user-service访问
    # 如何指定URL，参考资料
    user-service: /user/**
    auth-service: /auth/**
    order-service: /order/**
  # 忽略指定微服务
#  ignored-services: user-service, order-service
  # 可以使用 ‘*’ 忽略所有微服务，只路由上述指定的微服务
  ignored-services: '*'
  # 忽略包含aaa的url，包含明敏感路径
  ignored-patterns: /**/aaa/**
  # 指定全局敏感header,默认Cookie,Set-Cookie
  sensitive-headers: Cookie,Set-Cookie,Authorization
  # aaa,bbb不会被传播到其他微服务
#  ignored-headers: aaa,bbb
  # 需要使用下游的Spring Security的Header是，设置为false
#  ignore-security-headers: false
  # true禁用过滤器：PreRequestLogFilter
#  PreRequestFilter.pre.disable: true
#management:
#  security:
#    # 禁用actuator鉴权
#    enabled: false

---
spring:
  profiles: default
server:
  port: 1030

---
spring:
  profiles: peer2
server:
  port: 1031