spring:
  application:
    name: order-service
  kafka:
    admin:
      client-id: order-server
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    rabbitmq:
      queue: zipkin

logging:
  level:
    root: info

#management:
#  security:
#    # 禁用actuator鉴权
#    enabled: false

test:
  config: B

---
spring:
  profiles: default
server:
  port: 1111
---
spring:
  profiles: peer2
server:
  port: 1112

# 访问方式 http://admin:admin@localhost:1112
#security:
#  basic:
#    enabled: true
#  user:
#    name: user
#    password: password
#    role:
#    - USER
#  sessions: STATELESS
#  oauth2:
#    client:
#      clientId: order-service
#      clientSecret: ${security.user.password}
#      accessTokenUri: http://localhost:1090/oauth/token
#      grant-type: client_credentials
#      scope: server