spring:
  application:
    name: config-server
  cloud:
    config:
      label: develop
      server:
        git:
          uri: https://github.com/chendehe/SpringCloudWeb/
          search-paths: config-repo/
          username: chendehe
          password: ********
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  security:
    # 禁用actuator鉴权
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
---
spring:
  profiles: peer1
server:
  port: 1050
---
spring:
  profiles: peer2
server:
  port: 1051